version: 0.0
os: linux

files:
  - source: backend/expertFinder_backend
    destination: /var/www/html/

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_apache2.sh
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop_apache2.sh
      timeout: 300
      runas: root
