version: 0.0
os: linux

files:
  - source: backend/expertFinder_backend
    destination: /home/ubuntu/expertFinder_backend

hooks:
  BeforeInstall:
    - location: backend/scripts/install_dependencies.sh
      timeout: 300
      runas: root
